const chemstry = [

{q:"Smallest unit of matter?", a:"Atom", o:["Molecule","Atom","Cell","Electron"]},
{q:"Center of atom is called?", a:"Nucleus", o:["Electron","Nucleus","Proton","Shell"]},
{q:"Negatively charged particle?", a:"Electron", o:["Proton","Neutron","Electron","Ion"]},
{q:"Positively charged particle?", a:"Proton", o:["Electron","Neutron","Proton","Atom"]},
{q:"Particle with no charge?", a:"Neutron", o:["Electron","Proton","Neutron","Ion"]},
{q:"Number of protons in atom?", a:"Atomic number", o:["Mass number","Atomic number","Density","Valency"]},
{q:"Sum of protons and neutrons?", a:"Mass number", o:["Atomic number","Mass number","Density","Volume"]},
{q:"Substance made of one type of atom?", a:"Element", o:["Compound","Mixture","Element","Solution"]},
{q:"Combination of two or more elements?", a:"Compound", o:["Element","Compound","Mixture","Alloy"]},
{q:"Physical combination of substances?", a:"Mixture", o:["Compound","Element","Mixture","Molecule"]},

{q:"Symbol of Oxygen?", a:"O", o:["O","Ox","Og","Om"]},
{q:"Symbol of Hydrogen?", a:"H", o:["Hy","H","Hg","Hd"]},
{q:"Chemical formula of water?", a:"H2O", o:["HO","H2O","O2H","H3O"]},
{q:"Gas essential for breathing?", a:"Oxygen", o:["Nitrogen","Hydrogen","Oxygen","Carbon dioxide"]},
{q:"Gas used in photosynthesis?", a:"Carbon dioxide", o:["Oxygen","Nitrogen","Carbon dioxide","Hydrogen"]},
{q:"pH less than 7 indicates?", a:"Acid", o:["Base","Salt","Acid","Neutral"]},
{q:"pH more than 7 indicates?", a:"Base", o:["Acid","Base","Salt","Neutral"]},
{q:"pH equal to 7 indicates?", a:"Neutral", o:["Acid","Base","Neutral","Salt"]},
{q:"Substance that turns blue litmus red?", a:"Acid", o:["Base","Salt","Acid","Water"]},
{q:"Substance that turns red litmus blue?", a:"Base", o:["Acid","Salt","Base","Water"]},

{q:"Common salt formula?", a:"NaCl", o:["KCl","NaCl","Na2CO3","NaOH"]},
{q:"Acid present in lemon?", a:"Citric acid", o:["Acetic acid","Citric acid","Sulfuric acid","Nitric acid"]},
{q:"Acid present in vinegar?", a:"Acetic acid", o:["Citric acid","Acetic acid","Lactic acid","Carbonic acid"]},
{q:"Gas produced by burning fuel?", a:"Carbon dioxide", o:["Oxygen","Hydrogen","Carbon dioxide","Nitrogen"]},
{q:"Hardest natural substance?", a:"Diamond", o:["Gold","Iron","Diamond","Silver"]},
{q:"Process of solid to gas directly?", a:"Sublimation", o:["Evaporation","Condensation","Sublimation","Freezing"]},
{q:"Process of liquid to gas?", a:"Evaporation", o:["Freezing","Melting","Evaporation","Sublimation"]},
{q:"Process of gas to liquid?", a:"Condensation", o:["Evaporation","Condensation","Melting","Freezing"]},
{q:"Process of liquid to solid?", a:"Freezing", o:["Melting","Boiling","Freezing","Sublimation"]},
{q:"Boiling point of water?", a:"100°C", o:["0°C","50°C","100°C","212°C"]},

{q:"Freezing point of water?", a:"0°C", o:["0°C","32°C","100°C","-10°C"]},
{q:"Most abundant gas in air?", a:"Nitrogen", o:["Oxygen","Carbon dioxide","Nitrogen","Hydrogen"]},
{q:"Metal liquid at room temperature?", a:"Mercury", o:["Iron","Mercury","Copper","Gold"]},
{q:"Gas used in balloons?", a:"Helium", o:["Oxygen","Nitrogen","Helium","Carbon dioxide"]},
{q:"Rusting requires iron and?", a:"Oxygen and water", o:["Hydrogen","Nitrogen","Oxygen and water","Carbon"]},
{q:"Chemical reaction releasing heat?", a:"Exothermic", o:["Endothermic","Exothermic","Neutral","Physical"]},
{q:"Chemical reaction absorbing heat?", a:"Endothermic", o:["Exothermic","Endothermic","Neutral","Combustion"]},
{q:"Process of burning?", a:"Combustion", o:["Oxidation","Combustion","Reduction","Neutralization"]},
{q:"Substance that speeds up reaction?", a:"Catalyst", o:["Reactant","Product","Catalyst","Solvent"]},
{q:"Pure water is?", a:"Neutral", o:["Acidic","Basic","Neutral","Salt"]},

{q:"Chemical symbol of Gold?", a:"Au", o:["Ag","Au","Gd","Go"]},
{q:"Chemical symbol of Silver?", a:"Ag", o:["Au","Si","Ag","Sv"]},
{q:"Chemical symbol of Sodium?", a:"Na", o:["So","Sn","Na","S"]},
{q:"Chemical symbol of Potassium?", a:"K", o:["P","K","Po","Pt"]},
{q:"Chemical symbol of Iron?", a:"Fe", o:["Ir","Fe","In","I"]},
{q:"Water is example of?", a:"Compound", o:["Element","Mixture","Compound","Alloy"]},
{q:"Air is example of?", a:"Mixture", o:["Compound","Mixture","Element","Solution"]},
{q:"Substance dissolved in solution?", a:"Solute", o:["Solvent","Solute","Solution","Mixture"]},
{q:"Substance that dissolves solute?", a:"Solvent", o:["Solute","Solvent","Mixture","Compound"]},
{q:"Universal solvent?", a:"Water", o:["Alcohol","Water","Oil","Acid"]},

{q:"Gas causing global warming?", a:"Carbon dioxide", o:["Oxygen","Carbon dioxide","Nitrogen","Helium"]},
{q:"Ozone layer protects from?", a:"UV rays", o:["Infrared","UV rays","Gamma rays","X-rays"]},
{q:"Process of adding oxygen?", a:"Oxidation", o:["Reduction","Oxidation","Combustion","Fusion"]},
{q:"Loss of oxygen?", a:"Reduction", o:["Oxidation","Reduction","Combustion","Neutralization"]},
{q:"Chemical bond sharing electrons?", a:"Covalent bond", o:["Ionic bond","Covalent bond","Metallic bond","Hydrogen bond"]},
{q:"Chemical bond transfer electrons?", a:"Ionic bond", o:["Covalent bond","Ionic bond","Metallic bond","Peptide bond"]},
{q:"Number of electrons in neutral atom equals?", a:"Protons", o:["Neutrons","Protons","Ions","Mass number"]},
{q:"Atomic number of Hydrogen?", a:"1", o:["1","2","8","16"]},
{q:"Atomic number of Carbon?", a:"6", o:["6","8","12","14"]},
{q:"Atomic number of Oxygen?", a:"8", o:["6","7","8","9"]},

{q:"Periodic table arranged by?", a:"Atomic number", o:["Mass","Color","Atomic number","Density"]},
{q:"Horizontal rows in periodic table?", a:"Periods", o:["Groups","Periods","Blocks","Series"]},
{q:"Vertical columns in periodic table?", a:"Groups", o:["Periods","Groups","Rows","Lines"]},
{q:"Metals are good conductors of?", a:"Heat and electricity", o:["Light","Sound","Heat and electricity","Gas"]},
{q:"Non-metals are generally?", a:"Poor conductors", o:["Good conductors","Poor conductors","Shiny","Malleable"]},
{q:"Process of coating iron with zinc?", a:"Galvanization", o:["Rusting","Galvanization","Electrolysis","Distillation"]},
{q:"Separation by boiling point?", a:"Distillation", o:["Filtration","Distillation","Evaporation","Chromatography"]},
{q:"Separation of insoluble solid from liquid?", a:"Filtration", o:["Distillation","Filtration","Sublimation","Chromatography"]},
{q:"Separation based on color?", a:"Chromatography", o:["Filtration","Distillation","Chromatography","Evaporation"]},
{q:"Electrolysis uses?", a:"Electricity", o:["Heat","Pressure","Electricity","Light"]},

{q:"Gas used in welding?", a:"Acetylene", o:["Oxygen","Acetylene","Hydrogen","Nitrogen"]},
{q:"Main component of natural gas?", a:"Methane", o:["Ethane","Methane","Propane","Butane"]},
{q:"Alcohol used in drinks?", a:"Ethanol", o:["Methanol","Ethanol","Propanol","Butanol"]},
{q:"Strongest acid commonly used in lab?", a:"Sulfuric acid", o:["Acetic acid","Sulfuric acid","Citric acid","Carbonic acid"]},
{q:"Chemical formula of ammonia?", a:"NH3", o:["NH2","NH3","N2H","NO3"]},
{q:"Gas with rotten egg smell?", a:"Hydrogen sulfide", o:["Oxygen","Hydrogen sulfide","Carbon dioxide","Nitrogen"]},
{q:"Matter that has fixed volume and shape?", a:"Solid", o:["Liquid","Gas","Solid","Plasma"]},
{q:"Change from solid to liquid?", a:"Melting", o:["Freezing","Melting","Condensation","Sublimation"]},
{q:"Unit of concentration?", a:"Molarity", o:["Density","Volume","Molarity","Mass"]},
{q:"Study of carbon compounds?", a:"Organic chemistry", o:["Inorganic chemistry","Organic chemistry","Physical chemistry","Analytical chemistry"]}

];
export default Physics;
