const Physics = [

{q:"SI unit of force?", a:"Newton", o:["Joule","Newton","Watt","Pascal"]},
{q:"SI unit of work?", a:"Joule", o:["Watt","Joule","Newton","Volt"]},
{q:"SI unit of power?", a:"Watt", o:["Joule","Watt","Ampere","Ohm"]},
{q:"SI unit of force?", a:"Newton", o:["Joule","Newton","Watt","Pascal"]},
{q:"SI unit of work?", a:"Joule", o:["Watt","Joule","Newton","Volt"]},
{q:"SI unit of power?", a:"Watt", o:["Joule","Watt","Ampere","Ohm"]},
{q:"SI unit of pressure?", a:"Pascal", o:["Newton","Pascal","Bar","Joule"]},
{q:"SI unit of electric current?", a:"Ampere", o:["Volt","Ampere","Ohm","Watt"]},
{q:"SI unit of voltage?", a:"Volt", o:["Ampere","Volt","Ohm","Coulomb"]},
{q:"SI unit of resistance?", a:"Ohm", o:["Volt","Ohm","Watt","Ampere"]},
{q:"SI unit of energy?", a:"Joule", o:["Newton","Joule","Watt","Pascal"]},
{q:"Acceleration due to gravity on Earth?", a:"9.8 m/s²", o:["8.9 m/s²","9.8 m/s²","10.8 m/s²","7.8 m/s²"]},
{q:"Instrument used to measure temperature?", a:"Thermometer", o:["Barometer","Thermometer","Ammeter","Voltmeter"]},

{q:"Instrument used to measure current?", a:"Ammeter", o:["Voltmeter","Ammeter","Ohmmeter","Barometer"]},
{q:"Instrument used to measure voltage?", a:"Voltmeter", o:["Ammeter","Voltmeter","Thermometer","Hydrometer"]},
{q:"Instrument used to measure pressure?", a:"Barometer", o:["Thermometer","Barometer","Ammeter","Hygrometer"]},
{q:"Speed equals?", a:"Distance divided by time", o:["Time divided by distance","Distance divided by time","Mass times acceleration","Force divided by area"]},
{q:"Formula for force?", a:"Mass times acceleration", o:["Mass times acceleration","Force divided by area","Work divided by time","Voltage times current"]},
{q:"Unit of frequency?", a:"Hertz", o:["Hertz","Watt","Joule","Newton"]},
{q:"Time taken for one complete wave?", a:"Period", o:["Frequency","Amplitude","Period","Velocity"]},
{q:"Number of waves per second?", a:"Frequency", o:["Period","Frequency","Amplitude","Speed"]},
{q:"Device that converts electrical energy to mechanical energy?", a:"Electric motor", o:["Generator","Electric motor","Transformer","Battery"]},
{q:"Device that converts mechanical energy to electrical energy?", a:"Generator", o:["Motor","Generator","Transformer","Resistor"]},

{q:"Law stating every action has equal reaction?", a:"Newton third law", o:["Newton first law","Newton second law","Newton third law","Ohm law"]},
{q:"Law of inertia is?", a:"Newton first law", o:["Newton first law","Newton second law","Newton third law","Faraday law"]},
{q:"Relationship between voltage current and resistance?", a:"Ohm law", o:["Newton law","Ohm law","Boyle law","Hooke law"]},
{q:"Unit of electric charge?", a:"Coulomb", o:["Volt","Coulomb","Ampere","Ohm"]},
{q:"Energy stored in stretched spring?", a:"Elastic potential energy", o:["Kinetic energy","Elastic potential energy","Chemical energy","Thermal energy"]},
{q:"Energy due to motion?", a:"Kinetic energy", o:["Potential energy","Kinetic energy","Heat energy","Sound energy"]},
{q:"Energy due to position?", a:"Potential energy", o:["Kinetic energy","Potential energy","Light energy","Electrical energy"]},
{q:"Mirror that converges light?", a:"Concave mirror", o:["Convex mirror","Plane mirror","Concave mirror","Glass slab"]},
{q:"Mirror that diverges light?", a:"Convex mirror", o:["Concave mirror","Convex mirror","Plane mirror","Lens"]},
{q:"Lens that converges light?", a:"Convex lens", o:["Concave lens","Convex lens","Plane mirror","Prism"]},

{q:"Lens that diverges light?", a:"Concave lens", o:["Convex lens","Concave lens","Plane mirror","Prism"]},
{q:"Splitting of white light?", a:"Dispersion", o:["Reflection","Refraction","Dispersion","Diffraction"]},
{q:"Bending of light?", a:"Refraction", o:["Reflection","Refraction","Dispersion","Absorption"]},
{q:"Bouncing back of light?", a:"Reflection", o:["Refraction","Reflection","Diffusion","Dispersion"]},
{q:"SI unit of momentum?", a:"kg m/s", o:["Newton","kg m/s","Joule","Watt"]},
{q:"Product of mass and velocity?", a:"Momentum", o:["Force","Momentum","Energy","Power"]},
{q:"Rate of doing work?", a:"Power", o:["Energy","Force","Power","Pressure"]},
{q:"Work equals?", a:"Force times distance", o:["Force times distance","Mass times acceleration","Voltage times current","Pressure times area"]},
{q:"SI unit of mass?", a:"Kilogram", o:["Gram","Kilogram","Newton","Pound"]},
{q:"SI unit of length?", a:"Meter", o:["Centimeter","Meter","Kilometer","Mile"]},

{q:"SI unit of time?", a:"Second", o:["Minute","Hour","Second","Day"]},
{q:"SI unit of temperature?", a:"Kelvin", o:["Celsius","Fahrenheit","Kelvin","Joule"]},
{q:"Boiling point of water?", a:"100°C", o:["90°C","100°C","80°C","120°C"]},
{q:"Freezing point of water?", a:"0°C", o:["0°C","10°C","5°C","-5°C"]},
{q:"Force per unit area?", a:"Pressure", o:["Force","Pressure","Energy","Power"]},
{q:"Opposition to motion?", a:"Friction", o:["Gravity","Friction","Magnetism","Pressure"]},
{q:"Pull of Earth on objects?", a:"Gravity", o:["Magnetism","Gravity","Friction","Pressure"]},
{q:"Device used to step up voltage?", a:"Transformer", o:["Generator","Transformer","Motor","Battery"]},
{q:"Material that allows electricity easily?", a:"Conductor", o:["Insulator","Conductor","Resistor","Semiconductor"]},
{q:"Material that resists electricity?", a:"Insulator", o:["Conductor","Insulator","Semiconductor","Wire"]},
{q:"Unit of magnetic field strength?", a:"Tesla", o:["Tesla","Weber","Henry","Farad"]},
{q:"Unit of capacitance?", a:"Farad", o:["Ohm","Farad","Henry","Tesla"]},
{q:"Unit of inductance?", a:"Henry", o:["Henry","Volt","Ampere","Coulomb"]},
{q:"Unit of power in electric circuit?", a:"Watt", o:["Joule","Watt","Volt","Ohm"]},
{q:"Speed of light in vacuum?", a:"3×10^8 m/s", o:["3×10^6 m/s","3×10^8 m/s","3×10^5 m/s","3×10^7 m/s"]},
{q:"Device used to measure resistance?", a:"Ohmmeter", o:["Voltmeter","Ammeter","Ohmmeter","Thermometer"]},
{q:"Opposition to electric current?", a:"Resistance", o:["Voltage","Resistance","Power","Charge"]},
{q:"Flow of electric charge?", a:"Electric current", o:["Voltage","Electric current","Resistance","Energy"]},
{q:"Combination of resistors in single path?", a:"Series", o:["Parallel","Series","Mixed","Open"]},
{q:"Combination of resistors with multiple paths?", a:"Parallel", o:["Series","Parallel","Closed","Simple"]},

{q:"Heat transfer through solids?", a:"Conduction", o:["Conduction","Convection","Radiation","Evaporation"]},
{q:"Heat transfer through fluids?", a:"Convection", o:["Radiation","Conduction","Convection","Reflection"]},
{q:"Heat transfer without medium?", a:"Radiation", o:["Conduction","Convection","Radiation","Diffusion"]},
{q:"Energy possessed by moving object?", a:"Kinetic energy", o:["Potential energy","Kinetic energy","Sound energy","Light energy"]},
{q:"Energy stored in raised object?", a:"Gravitational potential energy", o:["Elastic energy","Kinetic energy","Gravitational potential energy","Thermal energy"]},
{q:"Change of liquid to gas?", a:"Evaporation", o:["Condensation","Evaporation","Freezing","Melting"]},
{q:"Change of gas to liquid?", a:"Condensation", o:["Evaporation","Condensation","Melting","Boiling"]},
{q:"Change of solid to liquid?", a:"Melting", o:["Freezing","Melting","Evaporation","Condensation"]},
{q:"Change of liquid to solid?", a:"Freezing", o:["Boiling","Freezing","Melting","Sublimation"]},
{q:"Change of solid directly to gas?", a:"Sublimation", o:["Melting","Freezing","Sublimation","Condensation"]},

{q:"Force that opposes motion between surfaces?", a:"Friction", o:["Gravity","Friction","Magnetism","Tension"]},
{q:"Stretching force through rope?", a:"Tension", o:["Friction","Tension","Gravity","Pressure"]},
{q:"SI unit of density?", a:"kg/m³", o:["kg/m³","N/m²","J/kg","m/s"]},
{q:"Density equals?", a:"Mass divided by volume", o:["Volume divided by mass","Mass divided by volume","Force divided by area","Distance divided by time"]},
{q:"Pressure in liquids increases with?", a:"Depth", o:["Temperature","Depth","Color","Mass"]},
{q:"Upward force in fluid?", a:"Upthrust", o:["Gravity","Friction","Upthrust","Pressure"]},
{q:"Principle of floating bodies?", a:"Archimedes principle", o:["Newton law","Ohm law","Archimedes principle","Hooke law"]},
{q:"Unit of sound frequency?", a:"Hertz", o:["Watt","Hertz","Pascal","Joule"]},
{q:"Highness or lowness of sound?", a:"Pitch", o:["Loudness","Pitch","Echo","Tone"]},
{q:"Reflection of sound?", a:"Echo", o:["Echo","Refraction","Dispersion","Vibration"]},

{q:"Natural source of light?", a:"Sun", o:["Bulb","Torch","Sun","Lamp"]},
{q:"Artificial source of light?", a:"Electric bulb", o:["Sun","Moon","Electric bulb","Star"]},
{q:"Unit of luminous intensity?", a:"Candela", o:["Lumen","Lux","Candela","Watt"]},
{q:"Device used to detect electric current?", a:"Galvanometer", o:["Ammeter","Voltmeter","Galvanometer","Thermometer"]},
{q:"Device that stores electric charge?", a:"Capacitor", o:["Resistor","Capacitor","Inductor","Transformer"]},
{q:"Law of conservation of energy states?", a:"Energy cannot be created or destroyed", o:["Energy is lost","Energy increases","Energy cannot be created or destroyed","Energy disappears"]},
{q:"Work done against gravity increases?", a:"Potential energy", o:["Kinetic energy","Sound energy","Potential energy","Heat energy"]},
{q:"Device used to measure atmospheric humidity?", a:"Hygrometer", o:["Barometer","Hygrometer","Thermometer","Hydrometer"]},
{q:"Unit of electric power consumption?", a:"Kilowatt-hour", o:["Watt","Kilowatt-hour","Joule","Volt"]},
{q:"Rate of change of velocity?", a:"Acceleration", o:["Speed","Acceleration","Force","Momentum"]},

{q:"Force that keeps planets in orbit?", a:"Gravitational force", o:["Magnetic force","Friction","Gravitational force","Electric force"]},
{q:"Device that splits light into spectrum?", a:"Prism", o:["Lens","Mirror","Prism","Glass slab"]},
{q:"Primary colors of light?", a:"Red Green Blue", o:["Red Blue Yellow","Red Green Blue","Yellow Green Blue","Red Yellow Green"]},
{q:"Charge of electron?", a:"Negative", o:["Positive","Negative","Neutral","Zero"]},
{q:"Charge of proton?", a:"Positive", o:["Negative","Positive","Neutral","Zero"]},
{q:"Neutral particle in atom?", a:"Neutron", o:["Proton","Electron","Neutron","Ion"]},
{q:"Center of atom?", a:"Nucleus", o:["Electron","Nucleus","Proton","Shell"]},
{q:"SI unit of electric field?", a:"N/C", o:["N/C","Volt","Ohm","Tesla"]},
{q:"Opposite charges?", a:"Attract", o:["Repel","Attract","Ignore","Neutralize"]},
{q:"Like charges?", a:"Repel", o:["Attract","Repel","Combine","Neutralize"]},

{q:"Device used to measure force?", a:"Spring balance", o:["Thermometer","Spring balance","Barometer","Ammeter"]},
{q:"SI unit of work rate?", a:"Watt", o:["Joule","Newton","Watt","Pascal"]},
{q:"Energy stored in fuel?", a:"Chemical energy", o:["Mechanical energy","Chemical energy","Light energy","Sound energy"]},
{q:"Movement of object around another object?", a:"Revolution", o:["Rotation","Revolution","Vibration","Oscillation"]},
{q:"Spinning of object on its axis?", a:"Rotation", o:["Revolution","Rotation","Translation","Reflection"]},
{q:"Time for one complete oscillation?", a:"Period", o:["Frequency","Period","Amplitude","Speed"]},
{q:"Maximum displacement in wave?", a:"Amplitude", o:["Frequency","Amplitude","Velocity","Wavelength"]},
{q:"Distance between two crests?", a:"Wavelength", o:["Amplitude","Wavelength","Frequency","Period"]},
{q:"SI unit of wavelength?", a:"Meter", o:["Meter","Second","Hertz","Joule"]},
{q:"Energy of moving air?", a:"Wind energy", o:["Solar energy","Wind energy","Chemical energy","Heat energy"]},

{q:"Device converting sound to electrical signals?", a:"Microphone", o:["Speaker","Microphone","Generator","Motor"]},
{q:"Device converting electrical signals to sound?", a:"Loudspeaker", o:["Microphone","Loudspeaker","Transformer","Battery"]},
{q:"Force that pulls objects to center in circular motion?", a:"Centripetal force", o:["Friction","Centripetal force","Gravity","Magnetism"]},
{q:"Outward apparent force in circular motion?", a:"Centrifugal force", o:["Centripetal force","Centrifugal force","Friction","Tension"]},
{q:"Unit of electric energy?", a:"Joule", o:["Watt","Joule","Volt","Ampere"]},
{q:"Device used to measure light intensity?", a:"Lux meter", o:["Lux meter","Thermometer","Barometer","Galvanometer"]},
{q:"SI unit of magnetic flux?", a:"Weber", o:["Tesla","Weber","Henry","Farad"]},
{q:"Heating effect of current discovered by?", a:"Joule", o:["Ohm","Newton","Joule","Faraday"]},
{q:"Law relating pressure and volume of gas?", a:"Boyle law", o:["Charles law","Boyle law","Ohm law","Hooke law"]},
{q:"Law relating temperature and volume of gas?", a:"Charles law", o:["Boyle law","Charles law","Newton law","Faraday law"]},

{q:"Energy from nucleus splitting?", a:"Nuclear energy", o:["Chemical energy","Nuclear energy","Heat energy","Sound energy"]},
{q:"Device used to detect radiation?", a:"Geiger counter", o:["Thermometer","Geiger counter","Barometer","Ammeter"]},
{q:"Current produced by changing magnetic field?", a:"Induced current", o:["Direct current","Alternating current","Induced current","Static current"]},
{q:"Unit of electric potential difference?", a:"Volt", o:["Ampere","Volt","Ohm","Watt"]},
{q:"Energy from the sun?", a:"Solar energy", o:["Wind energy","Solar energy","Hydro energy","Nuclear energy"]},
{q:"Unit of electric resistance?", a:"Ohm", o:["Volt","Ohm","Ampere","Coulomb"]},
{q:"Ratio of output work to input work?", a:"Efficiency", o:["Power","Energy","Efficiency","Momentum"]},
{q:"Machine that changes force direction?", a:"Pulley", o:["Lever","Pulley","Inclined plane","Wedge"]},
{q:"Simple machine with fulcrum?", a:"Lever", o:["Pulley","Lever","Screw","Wheel"]},
{q:"Sloping surface used to raise load?", a:"Inclined plane", o:["Pulley","Lever","Inclined plane","Wedge"]},

{q:"SI unit of electric capacitance?", a:"Farad", o:["Henry","Farad","Tesla","Weber"]},
{q:"Material attracted by magnet?", a:"Iron", o:["Copper","Aluminum","Iron","Plastic"]},
{q:"Like poles of magnet?", a:"Repel", o:["Attract","Repel","Combine","Neutralize"]},
{q:"Unlike poles of magnet?", a:"Attract", o:["Repel","Attract","Ignore","Separate"]},
{q:"Smallest unit of matter?", a:"Atom", o:["Molecule","Atom","Cell","Electron"]},
{q:"Particle orbiting nucleus?", a:"Electron", o:["Proton","Neutron","Electron","Ion"]},
{q:"SI unit of power?", a:"Watt", o:["Joule","Newton","Watt","Volt"]},
{q:"Energy transformation in generator?", a:"Mechanical to electrical", o:["Electrical to mechanical","Mechanical to electrical","Chemical to heat","Light to sound"]},
{q:"Energy transformation in motor?", a:"Electrical to mechanical", o:["Mechanical to electrical","Electrical to mechanical","Chemical to heat","Light to sound"]},
{q:"Unit of electric charge?", a:"Coulomb", o:["Volt","Ampere","Coulomb","Ohm"]},

{q:"Force acting on unit charge?", a:"Electric field", o:["Magnetic field","Electric field","Current","Voltage"]},
{q:"Energy possessed due to temperature?", a:"Thermal energy", o:["Chemical energy","Thermal energy","Mechanical energy","Light energy"]},
{q:"State of matter with definite volume but no shape?", a:"Liquid", o:["Solid","Liquid","Gas","Plasma"]},
{q:"State of matter with definite shape and volume?", a:"Solid", o:["Liquid","Solid","Gas","Plasma"]},
{q:"State of matter with no definite shape and volume?", a:"Gas", o:["Solid","Liquid","Gas","Plasma"]},
{q:"Mirror used in vehicles?", a:"Convex mirror", o:["Concave mirror","Plane mirror","Convex mirror","Lens"]},
{q:"Energy stored in battery?", a:"Chemical energy", o:["Electrical energy","Chemical energy","Heat energy","Sound energy"]},
{q:"Unit of force?", a:"Newton", o:["Joule","Newton","Watt","Pascal"]},
{q:"Law of stretching spring?", a:"Hooke law", o:["Ohm law","Hooke law","Newton law","Boyle law"]},
{q:"Force required to stop moving object?", a:"Friction", o:["Gravity","Friction","Magnetism","Pressure"]}
];
export default Physics;
